PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sepon: <http://www.semanticweb.org/zchero/ontologies/2023/11/SepsisOntology#>

DESCRIBE ?node WHERE {
    ?node rdf:type* / rdfs:subClassOf* sepon:Diagnostic_Biomarker .
} 